### Get all products
GET http://localhost:5000/bags

###Get Category based products
GET http://localhost:5000/bags/category/Mountain_Bags

### Add product to db.
POST http://localhost:5000/accounts
Content-Type: application/json

{
  "customer_name": "Mahatma Gandhi",
  "customer_email": "gandhigondho@gmail.com",
  "customer_img": "https://w7.pngwing.com/pngs/481/915/png-transparent-computer-icons-user-avatar-woman-avatar-computer-business-conversation-thumbnail.png",
  "customer_review": "I loved to use your bags, your service is great. Keep going and donate me for making India Free from oppression!"
}

### Get a product by id.
GET http://localhost:5000/bags/63ebc65bb4dad767806ae045

### Update a product by id.
PATCH  http://localhost:5000/bags/63ecec1f11d0f727c66505b9
Content-Type: application/json

{
  
}

### Delete a product by id.
DELETE   http://localhost:5000/customersReview/6401b95261ae1ec91e1e1e69

### Unknown API call , error check.

GET http://localhost:5000/xyz